export class RouterUrls {
  // 欢迎页面
  static readonly Splash = "pages/splash/view/Splash"
  // 登陆页面
  static readonly Login = "pages/login/view/Login"
  // 主页
  static readonly Index = "pages/main/view/Main"
  // 歌单详情页
  static readonly SongSheetDetail = "pages/songsheet/view/SongSheetDetail"
  // 音乐播放页面
  static readonly MusicPlay = "pages/play/view/MusicPlay"
  // 动态详情页
  static readonly DynamicDetail = "pages/dynamic/view/DynamicDetailPage"
  // 图片预览页
  static readonly PicturePreview = "pages/pics/view/PicturePreview"

}